[package]
name = "hslstop-rt"
version = "0.1.1"
authors = ["Antti Peltonen <antti.peltonen@iki.fi>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
graphql_client = "0.7"
failure = "0.1"
reqwest = "0.9"
dotenv = "0.13"
prettytable-rs = "0.8"
chrono = "0.4"
